### ISSUE TITLE
pip install with latest version of dbbackup (2.3.1) fails

### ISSUE THREAD

**Issue by ralphiee22** [django-dbbackup/django-dbbackup#120]
tried running pip install and I get the following error:
```python
Collecting django-dbbackup==2.3.1 (from -r requirements.txt (line 10))
/usr/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading django-dbbackup-2.3.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-9Ou1l9/django-dbbackup/setup.py", line 21, in <module>
        tests_require=get_test_requirements(),
      File "/tmp/pip-build-9Ou1l9/django-dbbackup/setup.py", line 11, in get_test_requirements
        return open('requirements-tests.txt').read().splitlines()
    IOError: [Errno 2] No such file or directory: 'requirements-tests.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9Ou1l9/django-dbbackup
```

**Comment by datakid** [comment]
Can confirm this bug.

**Comment by mjs7231** [comment]
Sorry. Need to add this file to MANIFEST.in. I'm at AWS re:Invent till this weekend.

**Comment by datakid** [comment]
This is still an issue.

**Comment by mjs7231** [comment]
Try again version 2.3.2

**Comment by datakid** [comment]
perfect, thanks.

**Comment by mjs7231** [comment]
Thanks for confirming! Sorry for the issue.
