### ISSUE TITLE
dbrestore looks for file in configured storage even when local file is specified

### ISSUE THREAD

**Issue by MattFisher** [django-dbbackup/django-dbbackup#124]
After manually downloading `xxx-xxx-2015-10-25-180000.psql.gz` from the configured s3 storage and uncompressing it to `xxx-xxx-2015-10-25-180000.psql` in the current directory, running the dbrestore command still looks for the file in the s3 bucket (and it isn't there because the compressed version is but not the uncompressed one).
Is this behaviour as designed (expecting a local file storage to be configured) or unintentional?

Traceback:
```
./manage.py dbrestore -f xxx-xxx-2015-10-25-180000.psql
Restoring backup for database: xxx
[2015-10-28 16:35:39,807] INFO dbrestore [dbbackup.command:76] Restoring backup for database: xxx
Restoring: xxx-xxx-2015-10-25-180000.psql
[2015-10-28 16:35:39,808] INFO dbrestore [dbbackup.command:86] Restoring: xxx-xxx-2015-10-25-180000.psql
Reading file xxx-xxx-2015-10-25-180000.psql
Reading file xxx-xxx-2015-10-25-180000.psql
Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/apps/staging/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/srv/apps/staging/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/apps/staging/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/srv/apps/staging/env/local/lib/python2.7/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/srv/apps/staging/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/srv/apps/staging/env/local/lib/python2.7/site-packages/dbbackup/management/commands/dbrestore.py", line 58, in handle
    self.restore_backup()
  File "/srv/apps/staging/env/local/lib/python2.7/site-packages/dbbackup/management/commands/dbrestore.py", line 88, in restore_backup
    inputfile = self.storage.read_file(input_filename)
  File "/srv/apps/staging/env/local/lib/python2.7/site-packages/dbbackup/storage/builtin_django.py", line 39, in read_file
    return self.storage.open(name=filepath, mode='rb')
  File "/srv/apps/staging/env/local/lib/python2.7/site-packages/django/core/files/storage.py", line 35, in open
    return self._open(name, mode)
  File "/srv/apps/staging/env/local/lib/python2.7/site-packages/storages/backends/s3boto.py", line 383, in _open
    raise IOError('File does not exist: %s' % name)
IOError: File does not exist: xxx-xxx-2015-10-25-180000.psql
```

**Comment by ZuluPro** [comment]
In its design dbbackup must upload backup and be able to restore the same in an agnostic way.
You don't need to download or extract yourself backup files. `-f` allows to choose remote file.

If you push to s3, you must pull from, but I think it could be a great feature to restore from a file on local file system.

**Comment by MattFisher** [comment]
Okay, I think the documentation says -f specifies a "local file", which is
what misled me.

I tried restoring directly from s3 but that failed due to running out of
memory because the backup file was several hundred MB (see the other issue
I raised).

**Comment by ZuluPro** [comment]
Hello @MattFisher,
Maybe this issue's solution can resolve your trouble: https://github.com/django-dbbackup/django-dbbackup/issues/146

**Comment by ZuluPro** [comment]
Hello @MattFisher,
Is this issue is still relevant ?

**Comment by MattFisher** [comment]
Looks like #146 solves it. Thanks!
