### ISSUE TITLE
Issue with dbrestore

### ISSUE THREAD

**Issue by psychok7** [django-dbbackup/django-dbbackup#138]
So i just updated dbbackup from version `2.0.4` to version `2.3.2` so i could get the no `--noinput` (https://github.com/django-dbbackup/django-dbbackup/pull/99) option when i `dbrestore` but i am running into this issue:

```
root@f0c2e40cdef6:/vagrant# python manage.py dbrestore --noinput --settings=xxx.settings.local
Restoring backup for database: postgres
Finding latest backup
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/dbbackup/management/commands/dbrestore.py", line 58, in handle
    self.restore_backup()
  File "/usr/local/lib/python2.7/dist-packages/dbbackup/management/commands/dbrestore.py", line 82, in restore_backup
    compressed=self.uncompress)
  File "/usr/local/lib/python2.7/dist-packages/dbbackup/storage/base.py", line 148, in get_latest_backup
    return max(files, key=utils.filename_to_date)
  File "/usr/local/lib/python2.7/dist-packages/dbbackup/utils.py", line 373, in filename_to_date
    datestring = filename_to_datestring(filename, datefmt)
  File "/usr/local/lib/python2.7/dist-packages/dbbackup/utils.py", line 358, in filename_to_datestring
    return search.groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'

```

Any ideas? Last time i tested this was with the master at the time

**Comment by psychok7** [comment]
Just realized a normal dbrestore throws the same error.

**Comment by psychok7** [comment]
same issue with current master

**Comment by ZuluPro** [comment]
Ok, can you give me:
- Your ``DBBACKUP_DATE_FORMAT``
- Your  ``DBBACKUP_FILENAME_TEMPLATE``
 ?

**Comment by psychok7** [comment]
@ZuluPro i don't have that set, so i am assuming its the default values. i tried explicily adding them now and same problem:

```
DBBACKUP_BACKUP_DIRECTORY = os.path.join(BASE_DIR, 'xxx_management/backups/')
DBBACKUP_CLEANUP_KEEP = 1
DBBACKUP_CLEANUP_KEEP_MEDIA = 1
DBBACKUP_DATE_FORMAT = '%Y-%m-%d-%H%M%S'
DBBACKUP_FILENAME_TEMPLATE = '{databasename}-{servername}-{datetime}.{extension}'
```

**Comment by ZuluPro** [comment]
Could you give your backup filename ?
When did you create the backup file ?

**Comment by psychok7** [comment]
@ZuluPro i created it today but with the previous version `2.0.4`. Only updated to version `2.3.2` after. its called `default.backup`

**Comment by ZuluPro** [comment]
Hmmmm, it should contain date time for sort by this. I'm on it.

Anthony Monthe - Open source enthousiaste
anthony-monthe.me

**Comment by ZuluPro** [comment]
@psychok7: Could you create one with new version please ?

**Comment by psychok7** [comment]
@ZuluPro with the new version it created differently in fact. but the restore still does not work:

```
root@4d3025cd709e:/vagrant# python manage.py dbbackup --settings=xx.settings.local
Backing Up Database: postgres
Running: pg_dump --username=****** --host=xx_postgis --port=5432 ******
Backup tempfile created: 5.4 MB
Writing file to FileSystemStorage: <bound method Storage.backup_dir of <dbbackup.storage.filesystem_storage.Storage object at 0x7fc0523545d0>>, filename: postgres-4d3025cd709e-2015-12-16-175329.psql
Writing file postgres-4d3025cd709e-2015-12-16-175329.psql
Writing file postgres-4d3025cd709e-2015-12-16-175329.psql
root@4d3025cd709e:/vagrant# python manage.py dbrestore --settings=xx.settings.local
Restoring backup for database: postgres
Finding latest backup
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/dbbackup/management/commands/dbrestore.py", line 58, in handle
    self.restore_backup()
  File "/usr/local/lib/python2.7/dist-packages/dbbackup/management/commands/dbrestore.py", line 82, in restore_backup
    compressed=self.uncompress)
  File "/usr/local/lib/python2.7/dist-packages/dbbackup/storage/base.py", line 148, in get_latest_backup
    return max(files, key=utils.filename_to_date)
  File "/usr/local/lib/python2.7/dist-packages/dbbackup/utils.py", line 373, in filename_to_date
    datestring = filename_to_datestring(filename, datefmt)
  File "/usr/local/lib/python2.7/dist-packages/dbbackup/utils.py", line 358, in filename_to_datestring
    return search.groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by ManuelGysin** [comment]
Have a look at #139, this should fix this problem.
