### ISSUE TITLE
dbbackup FileNotFoundError WinError 2 on first time use

### ISSUE THREAD

**Issue by Braintelligence** [django-dbbackup/django-dbbackup#149]
Hello everyone. I'm using dbbackup on Windows with these settings:

```python
DBBACKUP_STORAGE = 'dbbackup.storage.filesystem_storage'
DBBACKUP_STORAGE_OPTIONS = {'location': 'D:\\my\\dir\\backupfolder'}
```

Trying to test dbbackup this happens:

```
Backing Up Database: aristokratismus_pgdb
Running: pg_dump --username=aristokratismus_app --host=localhost --port=5432 ari
stokratismus_pgdb
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "D:\CLOUD\GoogleDrive\_ARISTOKRATISMUS\aristokratismus_env\lib\site-packa
ges\django\core\management\__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "D:\CLOUD\GoogleDrive\_ARISTOKRATISMUS\aristokratismus_env\lib\site-packa
ges\django\core\management\__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\CLOUD\GoogleDrive\_ARISTOKRATISMUS\aristokratismus_env\lib\site-packa
ges\django\core\management\base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "D:\CLOUD\GoogleDrive\_ARISTOKRATISMUS\aristokratismus_env\lib\site-packa
ges\django\core\management\base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "D:\CLOUD\GoogleDrive\_ARISTOKRATISMUS\aristokratismus_env\lib\site-packa
ges\dbbackup\utils.py", line 96, in wrapper
    func(*args, **kwargs)
  File "D:\CLOUD\GoogleDrive\_ARISTOKRATISMUS\aristokratismus_env\lib\site-packa
ges\dbbackup\management\commands\dbbackup.py", line 54, in handle
    self.save_new_backup(database)
  File "D:\CLOUD\GoogleDrive\_ARISTOKRATISMUS\aristokratismus_env\lib\site-packa
ges\dbbackup\management\commands\dbbackup.py", line 70, in save_new_backup
    self.dbcommands.run_backup_commands(outputfile)
  File "D:\CLOUD\GoogleDrive\_ARISTOKRATISMUS\aristokratismus_env\lib\site-packa
ges\dbbackup\dbcommands.py", line 292, in run_backup_commands
    return self.run_commands(self.settings.BACKUP_COMMANDS, stdout=stdout)
  File "D:\CLOUD\GoogleDrive\_ARISTOKRATISMUS\aristokratismus_env\lib\site-packa
ges\dbbackup\dbcommands.py", line 308, in run_commands
    self.run_command(command, stdin, stdout)
  File "D:\CLOUD\GoogleDrive\_ARISTOKRATISMUS\aristokratismus_env\lib\site-packa
ges\dbbackup\dbcommands.py", line 323, in run_command
    process = Popen(command, stdin=pstdin, stdout=pstdout, env=updated_osenv)
  File "C:\INSTALLATIONEN\LIBS\Python34\lib\subprocess.py", line 859, in __init_
_
    restore_signals, start_new_session)
  File "C:\INSTALLATIONEN\LIBS\Python34\lib\subprocess.py", line 1112, in _execu
te_child
    startupinfo)
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finde
n
```

It looks like it switches from virtualenv to os level interpreter. Is that intended?

**Comment by Braintelligence** [comment]
Maybe related:
"In Windows , to use echo in subprocess, you would need to use shell=True . This is because echo is not a separate executable, but rather a built-in command for the windows command line." -> http://stackoverflow.com/questions/32268030/filenotfounderror-winerror-2-python-3-4

**Comment by ZuluPro** [comment]
Thanks for opening a issue.
I'll check it when I've got some time.

**Comment by Braintelligence** [comment]
Same app works on my Ubuntu 14.04 LTS webserver, though.

**Comment by vaibhav-jain** [comment]
@ZuluPro @Braintelligence I'm facing this issue too. With `shell=True` it works.

**Comment by ZuluPro** [comment]
@Braintelligence @vaibhav-jain 
Is your issue still relevant ?

**Comment by vaibhav-jain** [comment]
Nope.
