### ISSUE TITLE
ERROR:  invalid byte sequence for encoding "UTF8"

### ISSUE THREAD

**Issue by psychok7** [django-dbbackup/django-dbbackup#167]
Hey there, while trying `django-dbbackup==2.5.0` i ran into an error when doing a `dbrestore`. The workaround i found was to downgrade to `django-dbbackup==2.3.3`. I am using `Postgresql 9.3.9`

The traceback 

```
root@d536ecada160:/code# python proj/manage.py dbrestore --settings=proj.settings.prod
Restoring backup for database: postgres
Finding latest backup
Reading file info-projects-2016-06-08-103035.tar.gz
Reading file info-projects-2016-06-08-103035.tar.gz
Restoring: info-projects-2016-06-08-103035.tar.gz
Restore tempfile created: 35.8 MiB
Are you sure you want to continue? [Y/n]y
Running: dropdb --username=****** --host=proj_****** --port=5432 ******
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US.UTF-8",
	LC_ALL = "en_US.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Running: createdb --username=****** --owner=****** --host=proj_****** --port=5432 ******
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US.UTF-8",
	LC_ALL = "en_US.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Running: psql -d ****** -f - --username=****** --host=proj_****** --port=5432 --single-transaction
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US.UTF-8",
	LC_ALL = "en_US.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
psql:<stdin>:5: invalid command \r��-e��H�q
psql:<stdin>:10: invalid command \
psql:<stdin>:14: invalid command \]������8:+����(<�A 

...
psql:<stdin>:498: invalid command \ѐԹ�
psql:<stdin>:499: invalid command \�%�@
psql:<stdin>:503: ERROR:  invalid byte sequence for encoding "UTF8": 0xbc
psql:<stdin>:504: invalid command \��3�yhI�Q��
psql:<stdin>:506: invalid command \��fd=}�YM�
psql:<stdin>:507: invalid command \B�?��n0������8k:[7[�>#}E�9Ep"��BI�*����h%t�S�ƣ��_z��Nu����lOd���`ع3
psql:<stdin>:511: invalid command \q���Ja��.R
psql:<stdin>:58031: ERROR:  invalid byte sequence for encoding "UTF8": 0xf0 0x3c 0xbf 0xf9
```

Any ideas where this bug was introduced or how to fix it?

**Comment by ZuluPro** [comment]
Hello @psychok7, thank for this issue.
Did you try the answers of this [question](http://stackoverflow.com/questions/2499794/how-can-i-fix-a-locale-warning-from-perl) ?
I think error comes from your system settings, is it work on a dev environment ?

Otherwise, we had currently refactored the dbcommand system, this is in master branch,
Maybe it will work with this version ?

**Comment by psychok7** [comment]
@ZuluPro i did try those anwers before downgrading with no luck. Its a staging environment but if it was my issue it would not work with the previous version of dbbackup as well right?

I haven't tried the master branch yet, not sure i will be able to test it so soon

**Comment by ZuluPro** [comment]
@psychok7 Do you always have your trouble ?

**Comment by psychok7** [comment]
@ZuluPro i can let you know tomorrow by installing the latest version on another DB i have

**Comment by ZuluPro** [comment]
@psychok7, it will be useless, I experienced your error and try to make a patch for this tonight.

**Comment by ZuluPro** [comment]
@psychok7 Do you always have this issue with master ?

**Comment by psychok7** [comment]
@ZuluPro i had this problem with Master of `Jun 8` but i haven't tried it after that since i went back to `2.3.3`
I will only be able to try it again in about a week if you need me to.

**Comment by ZuluPro** [comment]
@psychok7 Any news ?

**Comment by psychok7** [comment]
@ZuluPro i upgraded from 2.3.3 to the current master but i am getting an error when i dbbackup so i am unable to test it yet..

i get a:

```
root@ef72136da23f:/vagrant# python manage.py dbbackup --settings=yy.settings.local
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/dbbackup/utils.py", line 96, in wrapper
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dbbackup/management/commands/dbbackup.py", line 51, in handle
    self.storage = get_storage()
  File "/usr/local/lib/python2.7/dist-packages/dbbackup/storage.py", line 30, in get_storage
    return Storage(path, **options)
  File "/usr/local/lib/python2.7/dist-packages/dbbackup/storage.py", line 62, in __init__
    self.storageCls = get_storage_class(self._storage_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/files/storage.py", line 328, in get_storage_class
    return import_string(import_path or settings.DEFAULT_FILE_STORAGE)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/module_loading.py", line 33, in import_string
    six.reraise(ImportError, ImportError(msg), sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/module_loading.py", line 29, in import_string
    return getattr(module, class_name)
ImportError: Module "dbbackup.storage" does not define a "filesystem_storage" attribute/class
```

Any ideas?

**Comment by ZuluPro** [comment]
@psychok7 
Oh yeah sorry, I merge the doc tonight. It has a upgrade guide.
DBBACKUP_STORAGE must now be a path to a Django Storage class.

**Comment by psychok7** [comment]
@ZuluPro oh ok, i fixed the storage issue by adding the following and the current Master seems to be working properly now
```
DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
DBBACKUP_STORAGE_OPTIONS = {'location': '/var/backups'}
```
