### ISSUE TITLE
Dropbox | 'NameError: name 'PP6*** *** ***jDI' is not defined'

### ISSUE THREAD

**Issue by tarasinf** [django-dbbackup/django-dbbackup#177]
**When I tried to make this flow:**
`python manage.py dbbackup`
1. Go to: https://www.dropbox.com/1/oauth2/authorize?response_type=code&client_id=e*** *** ***y
2. Click 'Allow' (you might have to log in first)
3. Copy the authorization code.

**On the 3-th step I got the next error:**
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/dbbackup/utils.py", line 96, in wrapper
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dbbackup/management/commands/dbbackup.py", line 50, in handle
    self.storage = BaseStorage.storage_factory()
  File "/usr/local/lib/python2.7/dist-packages/dbbackup/storage/base.py", line 62, in storage_factory
    return get_storage()
  File "/usr/local/lib/python2.7/dist-packages/dbbackup/storage/base.py", line 32, in get_storage
    return storage_module.Storage(**options)
  File "/usr/local/lib/python2.7/dist-packages/dbbackup/storage/dropbox_storage.py", line 37, in __init__
    self.dropbox = self.get_dropbox_client()
  File "/usr/local/lib/python2.7/dist-packages/dbbackup/storage/dropbox_storage.py", line 164, in get_dropbox_client
    access_token = self.get_access_token(flow)
  File "/usr/local/lib/python2.7/dist-packages/dbbackup/storage/dropbox_storage.py", line 171, in get_access_token
    return self.create_access_token(flow)
  File "/usr/local/lib/python2.7/dist-packages/dbbackup/storage/dropbox_storage.py", line 180, in create_access_token
    code = input("Enter the authorization code here: ").strip()
  File "<string>", line 1, in <module>
NameError: name 'PP6*** *** ***jDI' is not defined`
```

**Someone have any idea?** 
Thanks

**Comment by ZuluPro** [comment]
@tarasinf Did you find a solution ?

**Comment by tarasinf** [comment]
@ZuluPro No, I deprioritized this task( Dou you have the same problem? If you will find some solution write there, please)

**Comment by ZuluPro** [comment]
@tarasinf 
The dropbox code is moved to django-storage. I made a PR to ensure it will work with DBBackup.
Do not hesitate to give 👍 for speed up merging.
