### ISSUE TITLE
mediabackup to Dropbox fails but dbbackup is working

### ISSUE THREAD

**Issue by juliensalinas** [django-dbbackup/django-dbbackup#215]
I upgraded from v2.5.0 to v3.0.2 and since then mediabackup to Dropbox has not worked anymore.
I get ReadTimeoutError

Here are the logs : 

```
2016-09-19 14:31:59 DEBUG: Backup size: 68.1 MiB
2016-09-19 14:31:59 INFO: Writing file to ssh-2016-09-19-143154.tar.gz
2016-09-19 14:31:59 DEBUG: Writing file ssh-2016-09-19-143154.tar.gz
2016-09-19 14:31:59 INFO: Starting new HTTPS connection (1): api.dropbox.com
2016-09-19 14:32:02 INFO: Starting new HTTPS connection (1): api-content.dropbox.com
2016-09-19 14:33:03 WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api-content.dropbox.com', port=443): Read timed out. (read timeout=60.0)",)': /1/files_put/auto/ssh-2016-09-19-143154.tar.gz?overwrite=False
2016-09-19 14:33:03 INFO: Starting new HTTPS connection (2): api-content.dropbox.com
2016-09-19 14:34:03 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api-content.dropbox.com', port=443): Read timed out. (read timeout=60.0)",)': /1/files_put/auto/ssh-2016-09-19-143154.tar.gz?overwrite=False
2016-09-19 14:34:03 INFO: Starting new HTTPS connection (3): api-content.dropbox.com
2016-09-19 14:35:04 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api-content.dropbox.com', port=443): Read timed out. (read timeout=60.0)",)': /1/files_put/auto/ssh-2016-09-19-143154.tar.gz?overwrite=False
2016-09-19 14:35:04 INFO: Starting new HTTPS connection (4): api-content.dropbox.com
```

dbbackup is working perfectly.
I have no idea whether the problem is coming from me, django-dbbackup, django-storages, or dropbox.

Can you please help ?

Thanks !

**Comment by ZuluPro** [comment]
Hello @juliensalinas 
Thank to report this issue.

Could you try to ``curl api-content.dropbox.com`` from your host ?

**Comment by juliensalinas** [comment]
Thanks @ZuluPro for your answer.

`curl api-content.dropbox.com` returns `{"error": "Not Found"}`

and here is my console traceback when I launch `python manage.py mediabackup` : 

Backup size: 77.9 MiB
Writing file to ssh-2016-09-19-191115.tar
Writing file ssh-2016-09-19-191115.tar
Writing file ssh-2016-09-19-191115.tar
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/home/python2.7/site-packages/dbbackup/utils.py", line 106, in wrapper
    body = reporter.get_traceback_html()
  File "/home/python2.7/site-packages/django/views/debug.py", line 384, in get_traceback_html
    return t.render(c)
  File "/home/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/python2.7/site-packages/django/template/debug.py", line 89, in render
    output = self.filter_expression.resolve(context)
  File "/home/python2.7/site-packages/django/template/base.py", line 674, in resolve
    new_obj = func(obj, *arg_vals)
  File "/home/python2.7/site-packages/django/template/defaultfilters.py", line 771, in date
    return formats.date_format(value, arg)
  File "/home/python2.7/site-packages/django/utils/formats.py", line 136, in date_format
    return dateformat.format(value, get_format(format or 'DATE_FORMAT', use_l10n=use_l10n))
  File "/home/python2.7/site-packages/django/utils/formats.py", line 110, in get_format
    for module in get_format_modules(lang):
  File "/home/python2.7/site-packages/django/utils/formats.py", line 82, in get_format_modules
    modules = _format_modules_cache.setdefault(lang, list(iter_format_modules(lang, settings.FORMAT_MODULE_PATH)))
  File "/home/lib/python2.7/site-packages/django/utils/formats.py", line 51, in iter_format_modules
    if not check_for_language(lang):
  File "/home/python2.7/site-packages/django/utils/translation/__init__.py", line 181, in check_for_language
    return _trans.check_for_language(lang_code)
  File "/home/python2.7/site-packages/django/utils/lru_cache.py", line 125, in wrapper
    result = user_function(*args, **kwds)
  File "/home/python2.7/site-packages/django/utils/translation/trans_real.py", line 409, in check_for_language
    if not language_code_re.search(lang_code):
TypeError: expected string or buffer

**Comment by ZuluPro** [comment]
What is your Django version ?
Do you have a specific configuration ?

**Comment by juliensalinas** [comment]
I am running Django 1.8

django-dbbackup 3.0.2
django-storages 1.5.1
dropbox 6.4.0
urllib3 1.16
requests 2.9.0
requests-oauthlib 0.6.2

Here are 3 other third-party apps I'm using in Django: 
hijack
compat	
localflavor

I am wondering whether the problem could come from urllib3 package ? Or requests ?
I tried to have a look to the django-dbbackup code as well as the django-storages code and it seems the dbbackup and mediabackup commands are very similar. So it is really surprising one is working and the other isn't...

**Comment by bahar** [comment]
Hi @juliensalinas, we are also facing the same issue. db backup works but media backup to dropbox is not working. Have you found a fix?

@ZuluPro our configuration is 

Django 1.9
django-dbbackup 3.0.3
django-storages 1.5.1
dropbox 6.9.0
urllib3 1.18
requests 2.9.1
requests-oauthlib 0.6.0

Media backup in the local storage works great btw.

**Comment by juliensalinas** [comment]
Hi @bahar, unfortunately I had to go back the previous version of dbbackup. I know it is not a sustaining solution though...
I spent quite a lot of time reviewing the django-dbbackup source code as well as django-storages and dropbox code, but I could not find where the problem is coming from.

**Comment by shamilbuzz** [comment]
Hello @ZuluPro,
 
**Issue Scenario for our case:**
While trying to upload media backup on Dropbox as **normal.tar** or **compressed.tar.gz,** we faced the same issue mentioned above.
After one hours of searching and testing, I have found an weird solution.
**Solution**:
We have updated the method named **_create_tar** of dbbackup/management/commands/mediabackup.py in following way:
We have used NamedTemporaryFile instead of default SpooledTemporaryFile like this way,
`fileobj = tempfile.NamedTemporaryFile()
`And then in **backup_mediafiles** method we have updated the starred line,
`if self.path is None:`
`**self.write_to_storage(open(tarball.name, 'rb'), filename)**`
`else:`
`self.storage.write_file(tarball, filename)`
What we did, is just sending the file content rather sending the file object as a whole.

So, please take a look at our solution and let us know if it's feasible solution or not. If the solution is ok, can we just make a pull request so that it will help us to keep pace with your plugin.

Thanks in Advance

**Comment by ZuluPro** [comment]
@juliensalinas 
Really sorry for my latency and thank you very much for your troubleshooting. I started to review the 3 projects too, but haven't a lot of time, sorry...
The main difference is the following:
- dbbackup try to write a `SpooledTemporaryFile``
- mediabackup try to write a  `SpooledTemporaryFile` opened & closed by `tarfile.open`

I'll look at it soon, sorry again...

@shamilbuzz 
``tempfile.NamedTemporaryFile`` isn't used here, because we want to speed up operations. But does your solution upload to Dropbox ?

**Comment by bahar** [comment]
@ZuluPro [replying on behalf of @shamilbuzz, both of us are working in the same project] yes it does.

**Comment by juliensalinas** [comment]
@ZuluPro : no worries, I do understand ;) Your tool is great anyway !

**Comment by patroqueeet** [comment]
+1

**Comment by patroqueeet** [comment]
I have the same issue. evaluated if adding a timeout to the storage options, but that was not accepted. what should I do?

**Comment by patroqueeet** [comment]
I just learned that django-storages is using the deprecated Dropbox v1 API. is that known? can this be causing the problem? (ticket here https://github.com/jschneier/django-storages/issues/227)

**Comment by patroqueeet** [comment]
alright, I ventured to fork and migrate (in a rush, don't ask for extensive testing) to dropbox v2. it worked for my simple needs. fork is here: https://github.com/patroqueeet/django-storages 

pr to dbbackup maintainer was issued.

**Comment by ZuluPro** [comment]
@patroqueeet 
Thank your very much for this informations.
I'll fix it soon.

**Comment by patroqueeet** [comment]
my bad. pr went to django-storages. sry for the typo.

**Comment by ZuluPro** [comment]
@patroqueeet I'm in both ;)

**Comment by patroqueeet** [comment]
ha! didn't know :)

**Comment by ZuluPro** [comment]
Hello all,
DBBackup V3.0.4 should now fix this error.
