### ISSUE TITLE
TypeError: initial_value must be unicode or None, not str - 2.0.3

### ISSUE THREAD

**Issue by mjs7231** [django-dbbackup/django-dbbackup#23]
2.0.3 s3 backup, reverted to 1.9.0 and it is working as expected
  
    Backing Up Database: tpg
      Running: pg_dump --username=tpg --host=127.0.0.1 --port=5432 tpg
      Backup tempfile created: 40.7 MB
      Writing file to AmazonS3: <bound method Storage.backup_dir of <dbbackup.storage.s3_storage.Storage instance at 0x4078368>>, filename: default.backup
    Traceback (most recent call last):
      File "manage.py", line 11, in <module>
        execute_from_command_line(sys.argv)
      File "/home/tpg/.virtualenvs/tpgenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
        utility.execute()
      File "/home/tpg/.virtualenvs/tpgenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/home/tpg/.virtualenvs/tpgenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
        self.execute(*args, **options.__dict__)
      File "/home/tpg/.virtualenvs/tpgenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
        output = self.handle(*args, **options)
      File "/home/tpg/.virtualenvs/tpgenv/local/lib/python2.7/site-packages/dbbackup/utils.py", line 54, in wrapper
        func(*args, **kwargs)
      File "/home/tpg/.virtualenvs/tpgenv/local/lib/python2.7/site-packages/dbbackup/management/commands/dbbackup.py", line 53, in handle
        self.save_new_backup(database, database_key)
      File "/home/tpg/.virtualenvs/tpgenv/local/lib/python2.7/site-packages/dbbackup/management/commands/dbbackup.py", line 74, in save_new_backup
        self.storage.write_file(outputfile, filename)
      File "/home/tpg/.virtualenvs/tpgenv/local/lib/python2.7/site-packages/dbbackup/storage/s3_storage.py", line 63, in write_file
        tmpfile = StringIO(chunkdata)
    TypeError: initial_value must be unicode or None, not str

**Comment by mjs7231** [comment]
I think the fix for this is to replace StringIO with BytesIO.

**Comment by ZuluPro** [comment]
Outside of tests there's no more ``StringIO``:
```
$ grep -r StringIO
tests/commands/test_base.py:    from StringIO import StringIO
tests/commands/test_base.py:    from io import StringIO
tests/commands/test_base.py:        self.command.stdout = StringIO()
tests/test_utils.py:    from StringIO import StringIO
tests/test_utils.py:    from io import StringIO
tests/test_utils.py:        filehandle = StringIO('Test string')
tests/utils.py:    from StringIO import StringIO
tests/utils.py:    from io import StringIO
```
