### ISSUE TITLE
dbbackup command does not work with postgres

### ISSUE THREAD

**Issue by barrierwings-jay** [django-dbbackup/django-dbbackup#234]
I found out same issue and it is closed with saying that 'it is fixed with version 3.1.2

I am using django-dbbackup (3.1.3) with postgresql version 9.4

It has same error with closed issue #229 

```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\jaemyun\remann\logistics\logistic\myvenv\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "C:\Users\jaemyun\remann\logistics\logistic\myvenv\lib\site-packages\django\core\management\__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\jaemyun\remann\logistics\logistic\myvenv\lib\site-packages\django\core\management\base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\jaemyun\remann\logistics\logistic\myvenv\lib\site-packages\django\core\management\base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "C:\Users\jaemyun\remann\logistics\logistic\myvenv\lib\site-packages\dbbackup\utils.py", line 111, in wrapper
    func(*args, **kwargs)
  File "C:\Users\jaemyun\remann\logistics\logistic\myvenv\lib\site-packages\dbbackup\management\commands\dbbackup.py", line 61, in handle
    self._save_new_backup(database)
  File "C:\Users\jaemyun\remann\logistics\logistic\myvenv\lib\site-packages\dbbackup\management\commands\dbbackup.py", line 74, in _save_new_backup
    outputfile = self.connector.create_dump()
  File "C:\Users\jaemyun\remann\logistics\logistic\myvenv\lib\site-packages\dbbackup\db\base.py", line 80, in create_dump
    dump = self._create_dump()
  File "C:\Users\jaemyun\remann\logistics\logistic\myvenv\lib\site-packages\dbbackup\db\postgresql.py", line 36, in _create_dump
    stdout, stderr = self.run_command(cmd, env=self.dump_env)
  File "C:\Users\jaemyun\remann\logistics\logistic\myvenv\lib\site-packages\dbbackup\db\postgresql.py", line 20, in run_command
    return super(PgDumpConnector, self).run_command(*args, **kwargs)
  File "C:\Users\jaemyun\remann\logistics\logistic\myvenv\lib\site-packages\dbbackup\db\base.py", line 150, in run_command
    "Error running: {}\n{}".format(command, stderr.read()))
dbbackup.db.exceptions.CommandConnectorError: Error running:  pg_dump logistics_db --host=localhost --username=logistics_auth --no-password --clean
b'pg_dump: too many command-line arguments (first is "--host=localhost")\r\nTry "pg_dump --help" for more information.\r\n'
```

**Comment by ZuluPro** [comment]
Hello @barrierwings-jay 
Sorry for my latency,

Could you give me more informations:
Your DB & DBBackup configuration ?
What is your PostgreSQL server version ?
Could you try to launch these commands in shell:
` pg_dump logistics_db --host=localhost --username=logistics_auth --no-password --clean` (with whitespace in start)
`pg_dump logistics_db --host=localhost --username=logistics_auth --no-password --clean`

I think you'll need `PGPASSWORD` environment variable.

**Comment by ZuluPro** [comment]
@barrierwings-jay 
Any news ?

**Comment by miigotu** [comment]
```bash
manage.py@blah > dbbackup
bash -cl "/home/miigotu/Envs/blah/bin/python /home/miigotu/Applications/pycharm-2016.2.3/helpers/pycharm/django_manage.py dbbackup /home/miigotu/Projects/blah"
Backing Up Database: blah
Writing file to blah-2017-03-14-044730.psql

Process finished with exit code 0
```

@barrierwings-jay Works fine here, maybe you need to update psycopg2 
```bash
pip install -U psycopg2
```

**Comment by miigotu** [comment]
@goiOS he means if the user that you are logged in as does not have full access to administer the database, you should provide the username and password by other means because the dbbackup command does not accept those parameters. PGPASSWORD (and PGUSER) as environment variables are generally considered insecure ways to do this, but they are an option.

I would suggest using the `~/.pgpass` method to supply it

https://www.postgresql.org/docs/9.1/libpq-pgpass.html

**Comment by EhsanSafir** [comment]
> @barrierwings-jay
> Any news ?
that is work in my system
