### ISSUE TITLE
Dropbox integration stopped working

### ISSUE THREAD

**Issue by maxmalysh** [django-dbbackup/django-dbbackup#252]
Looks like an update of [django-storages](https://github.com/jschneier/django-storages) has broken Dropbox integration.

Package versions:
```
django-dbbackup==3.1.3
django-storages==1.6.3
dropbox==8.0.0
```

Stack trace:

```
(foobar-env) foobar@main:~/baz-website/foobar$ python3 manage.py mediabackup --compress
Writing file to main.foobar.org-2017-07-08-175710.tar.gz
TypeError: expected request_binary as binary type, got <class 'django.core.files.base.File'>
  File "/home/foobar/.env/foobar-env/lib/python3.5/site-packages/dbbackup/utils.py", line 111, in wrapper
    func(*args, **kwargs)
  File "/home/foobar/.env/foobar-env/lib/python3.5/site-packages/dbbackup/management/commands/mediabackup.py", line 52, in handle
    self.backup_mediafiles()
  File "/home/foobar/.env/foobar-env/lib/python3.5/site-packages/dbbackup/management/commands/mediabackup.py", line 103, in backup_mediafiles
    self.write_to_storage(tarball, filename)
  File "/home/foobar/.env/foobar-env/lib/python3.5/site-packages/dbbackup/management/commands/_base.py", line 88, in write_to_storage
    self.storage.write_file(file, path)
  File "/home/foobar/.env/foobar-env/lib/python3.5/site-packages/dbbackup/storage.py", line 82, in write_file
    self.storage.save(name=filename, content=filehandle)
  File "/home/foobar/.env/foobar-env/lib/python3.5/site-packages/django/core/files/storage.py", line 54, in save
    return self._save(name, content)
  File "/home/foobar/.env/foobar-env/lib/python3.5/site-packages/storages/backends/dropbox.py", line 111, in _save
    self.client.files_upload(content, self._full_path(name))
  File "/home/foobar/.env/foobar-env/lib/python3.5/site-packages/dropbox/base.py", line 1267, in files_upload
    f,
  File "/home/foobar/.env/foobar-env/lib/python3.5/site-packages/dropbox/dropbox.py", line 234, in request
    timeout=timeout)
  File "/home/foobar/.env/foobar-env/lib/python3.5/site-packages/dropbox/dropbox.py", line 325, in request_json_string_with_retry
    timeout=timeout)
  File "/home/foobar/.env/foobar-env/lib/python3.5/site-packages/dropbox/dropbox.py", line 369, in request_json_string
    type(request_binary))

Traceback (most recent call last):
  File "manage.py", line 24, in <module>
    execute_from_command_line(sys.argv)
  File "/home/foobar/.env/foobar-env/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/foobar/.env/foobar-env/lib/python3.5/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/foobar/.env/foobar-env/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/foobar/.env/foobar-env/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/foobar/.env/foobar-env/lib/python3.5/site-packages/dbbackup/utils.py", line 111, in wrapper
    func(*args, **kwargs)
  File "/home/foobar/.env/foobar-env/lib/python3.5/site-packages/dbbackup/management/commands/mediabackup.py", line 52, in handle
    self.backup_mediafiles()
  File "/home/foobar/.env/foobar-env/lib/python3.5/site-packages/dbbackup/management/commands/mediabackup.py", line 103, in backup_mediafiles
    self.write_to_storage(tarball, filename)
  File "/home/foobar/.env/foobar-env/lib/python3.5/site-packages/dbbackup/management/commands/_base.py", line 88, in write_to_storage
    self.storage.write_file(file, path)
  File "/home/foobar/.env/foobar-env/lib/python3.5/site-packages/dbbackup/storage.py", line 82, in write_file
    self.storage.save(name=filename, content=filehandle)
  File "/home/foobar/.env/foobar-env/lib/python3.5/site-packages/django/core/files/storage.py", line 54, in save
    return self._save(name, content)
  File "/home/foobar/.env/foobar-env/lib/python3.5/site-packages/storages/backends/dropbox.py", line 111, in _save
    self.client.files_upload(content, self._full_path(name))
  File "/home/foobar/.env/foobar-env/lib/python3.5/site-packages/dropbox/base.py", line 1267, in files_upload
    f,
  File "/home/foobar/.env/foobar-env/lib/python3.5/site-packages/dropbox/dropbox.py", line 234, in request
    timeout=timeout)
  File "/home/foobar/.env/foobar-env/lib/python3.5/site-packages/dropbox/dropbox.py", line 325, in request_json_string_with_retry
    timeout=timeout)
  File "/home/foobar/.env/foobar-env/lib/python3.5/site-packages/dropbox/dropbox.py", line 369, in request_json_string
    type(request_binary))
TypeError: expected request_binary as binary type, got <class 'django.core.files.base.File'>
```

See also:
- https://github.com/jschneier/django-storages/issues/227
- https://github.com/jschneier/django-storages/issues/301

**Comment by ZuluPro** [comment]
Hello @maxmalysh 
Is it really related to Dbbackup ?

**Comment by tporto** [comment]
I was having the same problem, it worked again when I updated these libs to a certain version.
dropbox==7.3.0
django-storages==1.5.2

**Comment by JakobGM** [comment]
I am still having this issue with:
```
dropbox==8.0.0
django-storages==1.6.5
```

**Comment by ZuluPro** [comment]
@JakobGM  Is it related to DBBackup ?

**Comment by JakobGM** [comment]
@ZuluPro I am not sure exactly where the issue lies, as I am unable to isolate the issue. But the exception is raised within the dropbox module, so it might not be related _directly_ to DBBackup.

**Comment by JakobGM** [comment]
Here is my exception:
```
TypeError: expected request_binary as binary type, got <class 'django.core.files.base.File'>
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "dbbackup/utils.py", line 111, in wrapper
    func(*args, **kwargs)
  File "dbbackup/management/commands/dbbackup.py", line 61, in handle
    self._save_new_backup(database)
  File "dbbackup/management/commands/dbbackup.py", line 88, in _save_new_backup
    self.write_to_storage(outputfile, filename)
  File "dbbackup/management/commands/_base.py", line 88, in write_to_storage
    self.storage.write_file(file, path)
  File "dbbackup/storage.py", line 82, in write_file
    self.storage.save(name=filename, content=filehandle)
  File "django/core/files/storage.py", line 54, in save
    return self._save(name, content)
  File "storages/backends/dropbox.py", line 111, in _save
    self.client.files_upload(content, self._full_path(name))
  File "dropbox/base.py", line 1267, in files_upload
    f,
  File "dropbox/dropbox.py", line 234, in request
    timeout=timeout)
  File "dropbox/dropbox.py", line 325, in request_json_string_with_retry
    timeout=timeout)
  File "dropbox/dropbox.py", line 369, in request_json_string
    type(request_binary))
```

**Comment by maxmalysh** [comment]
@ZuluPro I've found the error, it's inside `django-storages`. I'll provide a fix soon.

**Comment by flyalex** [comment]
Hi,
Any news regarding this issue?

**Comment by jfajardo** [comment]
pip uninstall django-storages
pip install -e 'git+https://github.com/jschneier/django-storages.git#egg=django-storages'
