### ISSUE TITLE
dbbackup fails on large object

### ISSUE THREAD

**Issue by KDemeul** [django-dbbackup/django-dbbackup#291]
### Description

We've recently updated our service from postgres 8.x to postgres 9.6.

Since then, we can not use the command `dbbackup` due to a "permission denied on a large object".

The logs are the following:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/dbbackup/utils.py", line 116, in wrapper
    func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/dbbackup/management/commands/dbbackup.py", line 61, in handle
    self._save_new_backup(database)
  File "/usr/local/lib/python3.5/site-packages/dbbackup/management/commands/dbbackup.py", line 74, in _save_new_backup
    outputfile = self.connector.create_dump()
  File "/usr/local/lib/python3.5/site-packages/dbbackup/db/base.py", line 76, in create_dump
    dump = self._create_dump()
  File "/usr/local/lib/python3.5/site-packages/dbbackup/db/postgresql.py", line 37, in _create_dump
    stdout, stderr = self.run_command(cmd, env=self.dump_env)
  File "/usr/local/lib/python3.5/site-packages/dbbackup/db/postgresql.py", line 21, in run_command
    return super(PgDumpConnector, self).run_command(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/dbbackup/db/base.py", line 144, in run_command
    "Error running: {}\n{}".format(command, stderr.read()))
dbbackup.db.exceptions.CommandConnectorError: Error running:  pg_dump postgres --host=db --port=5432 --username=postgres --no-password --clean
b'pg_dump: error reading large object 654: ERROR:  permission denied for large object 654\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/site-packages/dbbackup/utils.py", line 122, in wrapper
    logger.error(msg)
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1314, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1421, in _log
    self.handle(record)
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1431, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1493, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.5/logging/__init__.py", line 861, in handle
    self.emit(record)
  File "/usr/local/lib/python3.5/site-packages/dbbackup/log.py", line 48, in emit
    super(DbbackupAdminEmailHandler, self).emit(record)
  File "/usr/local/lib/python3.5/site-packages/django/utils/log.py", line 121, in emit
    self.send_mail(subject, message, fail_silently=True, html_message=html_message)
  File "/usr/local/lib/python3.5/site-packages/dbbackup/log.py", line 52, in send_mail
    utils.mail_admins(subject, message, *args, connection=self.connection(), **kwargs)
  File "/usr/local/lib/python3.5/site-packages/dbbackup/utils.py", line 103, in mail_admins
    mail.send(fail_silently=fail_silently)
  File "/usr/local/lib/python3.5/site-packages/django/core/mail/message.py", line 342, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/local/lib/python3.5/site-packages/post_office/backends.py", line 48, in send_messages
    headers=headers)
  File "/usr/local/lib/python3.5/site-packages/post_office/mail.py", line 82, in create
    email.save()
  File "/usr/local/lib/python3.5/site-packages/post_office/models.py", line 174, in save
    self.full_clean()
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 1248, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'subject': ['Ensure this value has at most 989 characters (it has 1280).']}
```

We are running our django service inside a docker container - running next to a postgres:9.6 service. 

Any hint on how to fix this?

**Comment by jonathan-s** [comment]
It looks like this is a permission issue, some changes to postgresql.conf described [here](https://stackoverflow.com/questions/40991185/postgresql-permission-denied-for-large-object) should make this work. Let me know if that is enough. I don't think there is anything that should be changed in this package.
