### ISSUE TITLE
fail backup postgres on windows 10

### ISSUE THREAD

**Issue by money71** [django-dbbackup/django-dbbackup#294]
**description**
postgres: `10`
PostgresRole: `SuperUser access`
django version : `1.11.16`
django-dbbackup version: `3.2.0`
python version: `Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)] on win32`

added postgres path to system environment path

```
DBBACKUP_CONNECTORS = {
    'default': {
        'USER': 'test',
        'PASSWORD': 'backuptest',
        'HOST': '127.0.0.1'
    }
}
```

when run 'python manage.py dbbackup' command on windows 10 get error but it's ok on ubuntu 18.04 

```
Backing Up Database: testdb
CommandConnectorError: Error running:  pg_dump testdb --host=127.0.0.1 --port=5432 --username=test --no-password --clean
[Error 2] The system cannot find the file specified
  File "D:\Projects\test_dbbackup\env\lib\site-packages\dbbackup\utils.py", line 116, in wrapper
    func(*args, **kwargs)
  File "D:\Projects\test_dbbackup\env\lib\site-packages\dbbackup\management\commands\dbbackup.py", line 61, in handle
    self._save_new_backup(database)
  File "D:\Projects\test_dbbackup\env\lib\site-packages\dbbackup\management\commands\dbbackup.py", line 74, in _save_new_backup
    outputfile = self.connector.create_dump()
  File "D:\Projects\test_dbbackup\env\lib\site-packages\dbbackup\db\base.py", line 76, in create_dump
    dump = self._create_dump()
  File "D:\Projects\test_dbbackup\env\lib\site-packages\dbbackup\db\postgresql.py", line 37, in _create_dump
    stdout, stderr = self.run_command(cmd, env=self.dump_env)
  File "D:\Projects\test_dbbackup\env\lib\site-packages\dbbackup\db\postgresql.py", line 21, in run_command
    return super(PgDumpConnector, self).run_command(*args, **kwargs)
  File "D:\Projects\test_dbbackup\env\lib\site-packages\dbbackup\db\base.py", line 150, in run_command
    "Error running: {}\n{}".format(command, str(err)))

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "D:\Projects\test_dbbackup\env\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "D:\Projects\test_dbbackup\env\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\Projects\test_dbbackup\env\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "D:\Projects\test_dbbackup\env\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "D:\Projects\test_dbbackup\env\lib\site-packages\dbbackup\utils.py", line 116, in wrapper
    func(*args, **kwargs)
  File "D:\Projects\test_dbbackup\env\lib\site-packages\dbbackup\management\commands\dbbackup.py", line 61, in handle
    self._save_new_backup(database)
  File "D:\Projects\test_dbbackup\env\lib\site-packages\dbbackup\management\commands\dbbackup.py", line 74, in _save_new_backup
    outputfile = self.connector.create_dump()
  File "D:\Projects\test_dbbackup\env\lib\site-packages\dbbackup\db\base.py", line 76, in create_dump
    dump = self._create_dump()
  File "D:\Projects\test_dbbackup\env\lib\site-packages\dbbackup\db\postgresql.py", line 37, in _create_dump
    stdout, stderr = self.run_command(cmd, env=self.dump_env)
  File "D:\Projects\test_dbbackup\env\lib\site-packages\dbbackup\db\postgresql.py", line 21, in run_command
    return super(PgDumpConnector, self).run_command(*args, **kwargs)
  File "D:\Projects\test_dbbackup\env\lib\site-packages\dbbackup\db\base.py", line 150, in run_command
    "Error running: {}\n{}".format(command, str(err)))
dbbackup.db.exceptions.CommandConnectorError: Error running:  pg_dump testdb --host=127.0.0.1 --port=5432 --username=backup --no-password --clean
[Error 2] The system cannot find the file specified
```

**Comment by ZuluPro** [comment]
So the issue is your windows system

**Comment by Abhijeet321** [comment]
I ran into the same error, anyone has the solution?

**Comment by sabbiu** [comment]
For anybody stumbling on this issue.

Issue is the name of database must be at last in the form
`pg_dump [options] db_name`

It seems to have already been fixed. But, it is not released as of `version 3.2.0`
[You can see the fix here](https://github.com/django-dbbackup/django-dbbackup/blob/master/dbbackup/db/postgresql.py#L36)

To use this in your project now,

1. Clone this repo somewhere outside your project folder
2. run `python setup.py install` in your environment
3. run `pip install paramiko django-storages` in your environment

**Comment by lclee3390** [comment]
Try to add the PostgreSQL bin directory path to the PATH environmental variable.
( Example : C:\Program Files\PostgreSQL\12\bin )

**Comment by 24thDawn** [comment]
For those coming from google.
Running "python manage.py dbbackup" with Admin privilege's in console will solve this.

**Comment by djangomcdjangerson** [comment]
For anyone coming from Google running MySQL or MariaDB rather than Postgres but still getting a CommandConnectorError, you need to add the directory for MysqlDump.exe to your path and restart your IDE or console. In my case, that directory was C:\Program Files\MariaDB 10.5\bin.

**Comment by emmetarries** [comment]
> Try to add the PostgreSQL bin directory path to the PATH environmental variable. ( Example : C:\Program Files\PostgreSQL\12\bin )

Pulling my hair out for a while over this same error, and adding the postgres bin to the path solved the issue for me! Thank you :)
