### ISSUE TITLE
dbrestore: AttributeError: 'tuple' object has no attribute 'read'

### ISSUE THREAD

**Issue by matburnham** [django-dbbackup/django-dbbackup#321]
Trying to use dbrestore to copy the database from my server to my local dev environment, falls over with the following error:

```
$ ./manage.py dbrestore --configuration=Dev --input-filename=../default-mydb-2020-02-22-230016.psql
Restoring backup for database 'default' and server 'None'
Restoring: ../default-mydb-2020-02-22-230016.psql
Traceback (most recent call last):
  File "./manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mat/.virtualenvs/mysite/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/mat/.virtualenvs/mysite/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/mat/.virtualenvs/mysite/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/mat/.virtualenvs/mysite/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/mat/.virtualenvs/mysite/lib/python3.6/site-packages/dbbackup/management/commands/dbrestore.py", line 54, in handle
    self._restore_backup()
  File "/home/mat/.virtualenvs/mysite/lib/python3.6/site-packages/dbbackup/management/commands/dbrestore.py", line 89, in _restore_backup
    self.logger.info("Restore tempfile created: %s", utils.handle_size(input_file))
  File "/home/mat/.virtualenvs/mysite/lib/python3.6/site-packages/dbbackup/utils.py", line 89, in handle_size
    filehandle.seek(0, 2)
  File "/home/mat/.virtualenvs/mysite/lib/python3.6/site-packages/django/core/files/utils.py", line 20, in <lambda>
    seek = property(lambda self: self.file.seek)
  File "/home/mat/.virtualenvs/mysite/lib/python3.6/site-packages/storages/backends/dropbox.py", line 45, in file
    copyfileobj(response, self._file)
  File "/home/mat/.virtualenvs/mysite/lib/python3.6/shutil.py", line 79, in copyfileobj
    buf = fsrc.read(length)
AttributeError: 'tuple' object has no attribute 'read'
```

While I'm using the dropbox backend, I'm just trying to load it locally.

**Comment by patroqueeet** [comment]
is there any solution known?

**Comment by patroqueeet** [comment]
> is there any solution known?

found my cause: forked `django-storages` lib. after upgrading it plus `dropbox` and `DBBackup` it all worked

**Comment by jonathan-s** [comment]
Was the issue in django-storages?

**Comment by patroqueeet** [comment]
@jonathan-s can't really prove it, but it smelled like my local `django-storages` fork was slightly outdated...

**Comment by jonathan-s** [comment]
Thanks, looking at the traceback it actually looks like it's the storage backend so I'm going to close this.
