### ISSUE TITLE
RemovedInDjango41Warning raised in Django 3.2 under pytest-django

### ISSUE THREAD

**Issue by johnthagen** [django-dbbackup/django-dbbackup#388]
# Bug Report

Our test suite runs with the following command:

```bash
$ python -Werror -m pytest
```

It errors due to a deprecation warning triggered by `dbbackup`:

```
Traceback (most recent call last):
  File "python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File ".tox/py39/lib/python3.9/site-packages/pytest/__main__.py", line 5, in <module>
    raise SystemExit(pytest.console_main())
  File ".tox/py39/lib/python3.9/site-packages/_pytest/config/__init__.py", line 185, in console_main
    code = main()
  File ".tox/py39/lib/python3.9/site-packages/_pytest/config/__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File ".tox/py39/lib/python3.9/site-packages/_pytest/config/__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File ".tox/py39/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File ".tox/py39/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File ".tox/py39/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File ".tox/py39/lib/python3.9/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File ".tox/py39/lib/python3.9/site-packages/_pytest/helpconfig.py", line 100, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File ".tox/py39/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File ".tox/py39/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File ".tox/py39/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File ".tox/py39/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1283, in parse
    self._preparse(args, addopts=addopts)
  File ".tox/py39/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1191, in _preparse
    self.hook.pytest_load_initial_conftests(
  File ".tox/py39/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File ".tox/py39/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File ".tox/py39/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File ".tox/py39/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File ".tox/py39/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File ".tox/py39/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File ".tox/py39/lib/python3.9/site-packages/pytest_django/plugin.py", line 348, in pytest_load_initial_conftests
    _setup_django()
  File ".tox/py39/lib/python3.9/site-packages/pytest_django/plugin.py", line 234, in _setup_django
    django.setup()
  File ".tox/py39/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File ".tox/py39/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File ".tox/py39/lib/python3.9/site-packages/django/apps/config.py", line 189, in create
    warnings.warn(message, RemovedInDjango41Warning, stacklevel=2)
django.utils.deprecation.RemovedInDjango41Warning: 'dbbackup' defines default_app_config = 'dbbackup.apps.DbbackupConfig'. Django now detects this configuration automatically. You can remove default_app_config.
```

Package versions:
- Python 3.9.5
- Django 3.2.3
- pytest-django 4.3.0
- django-dbbackup 3.3.0

**Comment by johnthagen** [comment]
`django-solo` fixed this with the following commit: https://github.com/lazybird/django-solo/commit/c1e4155a297219d0c9635619ecc348e3e52b54e9#diff-2abddaf8bebbd95da38fb188ff4e36ff2f52af3200e412399c02307929352abb
