### ISSUE TITLE
Type error with backup command

### ISSUE THREAD

**Issue by jesus2660** [django-dbbackup/django-dbbackup#47]
Found this error while trying to backup my database: 

Backing Up Database: scing_db
  Running: mysqldump --user=****** --password=****** --port=8001 scing_db
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line
338, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line
330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 390,
 in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 441,
 in execute
    output = self.handle(*args, **options)
  File "c:\users\jesus gomez\workspace\scing\src\django-dbbackup\dbbackup\utils.
py", line 62, in wrapper
    body = reporter.get_traceback_html()
  File "C:\Python27\lib\site-packages\django\views\debug.py", line 384, in get_t
raceback_html
    return t.render(c)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 209, in ren
der
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _re
nder
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in ren
der
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 79, in ren
der_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 89, in ren
der
    output = self.filter_expression.resolve(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 674, in res
olve
    new_obj = func(obj, *arg_vals)
  File "C:\Python27\lib\site-packages\django\template\defaultfilters.py", line 7
71, in date
    return formats.date_format(value, arg)
  File "C:\Python27\lib\site-packages\django\utils\formats.py", line 136, in dat
e_format
    return dateformat.format(value, get_format(format or 'DATE_FORMAT', use_l10n
=use_l10n))
  File "C:\Python27\lib\site-packages\django\utils\formats.py", line 110, in get
_format
    for module in get_format_modules(lang):
  File "C:\Python27\lib\site-packages\django\utils\formats.py", line 82, in get_
format_modules
    modules = _format_modules_cache.setdefault(lang, list(iter_format_modules(la
ng, settings.FORMAT_MODULE_PATH)))
  File "C:\Python27\lib\site-packages\django\utils\formats.py", line 51, in iter
_format_modules
    if not check_for_language(lang):
  File "C:\Python27\lib\site-packages\django\utils\translation\__init__.py", lin
e 181, in check_for_language
    return _trans.check_for_language(lang_code)
  File "C:\Python27\lib\site-packages\django\utils\lru_cache.py", line 125, in w
rapper
    result = user_function(*args, **kwds)
  File "C:\Python27\lib\site-packages\django\utils\translation\trans_real.py", l
ine 409, in check_for_language
    if not language_code_re.search(lang_code):
TypeError: expected string or buffer

on a side note: pip install doesn't include all the needed dependencies when installing this package and the docs are missing the necesary "six package" for said import to work

**Comment by MiiRaGe** [comment]
It seems to be a bug from django 1.8. 
https://code.djangoproject.com/ticket/24569

Updating to 1.8.2 fixed it for me.

**Comment by ZuluPro** [comment]
@benjaoming, I think this issue can be closed ?

**Comment by benjaoming** [comment]
Yeah, doesn't seem to be relevant anymore. Either it was six missing or it's the django 1.8.2 upgrade that fixes this.
