### ISSUE TITLE
AttributeError: 'module' object has no attribute 'filename_details'

### ISSUE THREAD

**Issue by luzfcb** [django-dbbackup/django-dbbackup#49]
[`utils`](https://github.com/mjs7231/django-dbbackup/blob/master/dbbackup/utils.py) module has not have a function named `filename_details` 
```bash
(projtest)luzfcb@oficina:~/projtest/$ python manage.py dbrestore -l
Listing backups on Filesystem in //home/luzfcb/projtest/db_backup:
  projtestdb-2015-06-09-161531.psql

Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/home/luzfcb/virtualenvs/projtest/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/luzfcb/virtualenvs/projtest/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/luzfcb/virtualenvs/projtest/local/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/luzfcb/virtualenvs/projtest/local/lib/python2.7/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/home/luzfcb/virtualenvs/projtest/local/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/home/luzfcb/virtualenvs/projtest/src/django-dbbackup/dbbackup/management/commands/dbrestore.py", line 56, in handle
    return self.list_backups()
  File "/home/luzfcb/virtualenvs/projtest/src/django-dbbackup/dbbackup/management/commands/dbrestore.py", line 156, in list_backups
    print(utils.filename_details(filepath))
AttributeError: 'module' object has no attribute 'filename_details'
```

**Comment by MiiRaGe** [comment]
What was this method supposed to do ? It's nowhere to be found.

**Comment by ZuluPro** [comment]
I think this issue is still relevant with actual code.
